### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by dreamflyings** [freechipsproject/diagrammer#22]
Are there any settings that can solve this problem?

[error] (run-main-0) java.lang.OutOfMemoryError: GC overhead limit exceeded
[error] java.lang.OutOfMemoryError: GC overhead limit exceeded
[error]         at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
[error]         at java.base/java.util.ArrayList.grow(ArrayList.java:237)
[error]         at java.base/java.util.ArrayList.grow(ArrayList.java:242)
[error] iagrammeat java.base/java.util.ArrayList.add(ArrayList.java:485)
[error]         at java.base/java.util.ArrayList.add(ArrayList.java:498)
[error]         at org.antlr.v4.runtime.ParserRuleContext.addAnyChild(ParserRuleContext.java:134)
[error]         at org.antlr.v4.runtime.ParserRuleContext.addChild(ParserRuleContext.java:139)
[error]         at org.antlr.v4.runtime.Parser.addContextToParseTree(Parser.java:617)
[error]         at org.antlr.v4.runtime.Parser.enterRule(Parser.java:629)
[error]         at firrtl.antlr.FIRRTLParser.field(FIRRTLParser.java:735)
[error]         at firrtl.antlr.FIRRTLParser.type(FIRRTLParser.java:661)
[error]         at firrtl.antlr.FIRRTLParser.stmt(FIRRTLParser.java:1216)
[error]         at firrtl.antlr.FIRRTLParser.simple_stmt(FIRRTLParser.java:1934)
[error]         at firrtl.antlr.FIRRTLParser.moduleBlock(FIRRTLParser.java:945)
[error]         at firrtl.antlr.FIRRTLParser.module(FIRRTLParser.java:298)
[error]         at firrtl.antlr.FIRRTLParser.circuit(FIRRTLParser.java:191)
[error]         at firrtl.Parser$.$anonfun$parseCharStream$1(Parser.scala:42)
[error]         at firrtl.Parser$$$Lambda$3983/0x0000000841342440.apply(Unknown Source)
[error]         at firrtl.Utils$.time(Utils.scala:169)
[error]         at firrtl.Parser$.parseCharStream(Parser.scala:33)
[error]         at firrtl.Parser$.parseString(Parser.scala:29)
[error]         at firrtl.Parser$.parse(Parser.scala:66)
[error]         at dotvisualizer.FirrtlDiagrammer$.run(FirrtlDiagrammer.scala:165)
[error]         at dotvisualizer.FirrtlDiagrammer$.main(FirrtlDiagrammer.scala:233)
[error]         at dotvisualizer.FirrtlDiagrammer.main(FirrtlDiagrammer.scala)
[err

**Comment by Aerotic** [comment]
The keyword is "java.lang.OutOfMemoryError"
I've met the almost same error.
 The reason is default memory reserved for java is limited to 4GiB.
To deal with this, I suggest that use `java -Xmx9999M -jar /your-path-to/sbt-launch.jar ++2.12.4 "runMain dotvisualizer.FirrtlDiagrammer $*" `rather than `sbt "runMain dotvisualizer.FirrtlDiagrammer $*"`, where the number 9999 should be greater than your available PC RAM  size
